"""Generate content drafts for marketing actions.

Uses an LLM if configured, otherwise falls back to rule-based templates.
"""

from .config import PromoterConfig
from .llm_adapter import LLMAdapter


class ContentGenerator:
    """Generate draft content for various promotion channels."""

    def __init__(self, config: PromoterConfig, llm: LLMAdapter | None = None) -> None:
        self.config = config
        self.llm = llm

    def _llm_or_fallback(
        self,
        system: str,
        user: str,
        fallback_fn,
    ) -> str:
        """Try LLM first, fall back to rule-based template on failure."""
        if self.llm and self.llm.is_available():
            try:
                return self.llm.generate(system, user) or fallback_fn()
            except Exception:
                return fallback_fn()
        return fallback_fn()

    def awesome_list_pr(self, list_name: str, list_url: str) -> str:
        """Generate a PR description for adding the project to an Awesome List."""
        name = self.config.project_name
        repo = f"https://github.com/{self.config.github_owner}/{self.config.github_repo}"
        desc = self.config.project_description
        url = self.config.project_url

        system = (
            "You are a marketing copywriter for open-source projects. "
            "Write concise, persuasive PR descriptions in Markdown."
        )
        user = (
            f"Write a PR description to add '{name}' to the Awesome List '{list_name}'.\n\n"
            f"Project: {name}\n"
            f"Description: {desc}\n"
            f"URL: {url}\n"
            f"Repo: {repo}\n"
            f"List URL: {list_url}\n\n"
            f"Include: what the project does, why it fits this list, license (Apache 2.0)."
        )

        def fallback():
            lines = [
                f"## Add {name} to {list_name}",
                "",
                f"| Field | Value |",
                f"|-------|-------|",
                f"| Name | [{name}]({repo}) |",
                f"| Website | {url} |",
                f"| Description | {desc} |",
                "",
                f"{name} is an open-source project that provides local-first persistent memory for AI agents.",
                "It includes global search, project context tracking, and MCP integration.",
                "",
                "**License:** Apache 2.0",
                "",
                "---",
                "",
                "*Draft generated by Truenex Promoter. Please review before submitting.*",
            ]
            return "\n".join(lines)

        return self._llm_or_fallback(system, user, fallback)

    def release_post(self, version: str, release_notes: str) -> str:
        """Generate a social media post for a new release."""
        name = self.config.project_name
        repo = f"https://github.com/{self.config.github_owner}/{self.config.github_repo}"

        system = (
            "You are a developer advocate. Write engaging, concise social media posts "
            "for open-source releases. Keep it authentic and developer-friendly."
        )
        user = (
            f"Write a social media post announcing {name} {version}.\n\n"
            f"Release notes:\n{release_notes[:800]}\n\n"
            f"Repo: {repo}\nWebsite: {self.config.project_url}"
        )

        def fallback():
            lines = [
                f"{name} {version} is out!",
                "",
                f"{self.config.project_description}",
                "",
                "What's new:",
                f"{release_notes[:300]}..." if len(release_notes) > 300 else release_notes,
                "",
                f"Check it out: {repo}",
                f"Docs: {self.config.project_url}",
                "",
                "#opensource #ai #memory #mcp #agents",
            ]
            return "\n".join(lines)

        return self._llm_or_fallback(system, user, fallback)

    def milestone_post(self, milestone: int, current_stars: int) -> str:
        """Generate a social media post for a star milestone."""
        name = self.config.project_name
        repo = f"https://github.com/{self.config.github_owner}/{self.config.github_repo}"

        system = (
            "You are a developer advocate. Write grateful, humble milestone announcements "
            "that feel authentic, not corporate. Thank the community genuinely."
        )
        user = (
            f"Write a social media post celebrating {name} reaching {current_stars} GitHub stars.\n\n"
            f"Repo: {repo}\nWebsite: {self.config.project_url}\n"
            f"Description: {self.config.project_description}"
        )

        def fallback():
            lines = [
                f"{name} just crossed {current_stars} stars on GitHub!",
                "",
                "Thank you to everyone who starred, forked, and contributed.",
                "",
                f"{self.config.project_description}",
                "",
                f"Star us: {repo}",
                f"Learn more: {self.config.project_url}",
                "",
                "#opensource #ai #memory #mcp #agents",
            ]
            return "\n".join(lines)

        return self._llm_or_fallback(system, user, fallback)

    def issue_response(self, issue_title: str, issue_body: str) -> str:
        """Generate a draft response to a new issue."""
        system = (
            "You are a helpful open-source maintainer. Draft thoughtful, empathetic "
            "responses to GitHub issues. Be helpful, ask clarifying questions if needed, "
            "and suggest next steps."
        )
        user = (
            f"Draft a response to this issue:\n\n"
            f"Title: {issue_title}\n"
            f"Body: {issue_body[:2000]}\n\n"
            f"Project: {self.config.project_name}"
        )

        def fallback():
            lines = [
                f"Thanks for opening this issue: **{issue_title}**",
                "",
                "I've reviewed the description and here are some initial thoughts:",
                "",
                "*(Draft response — human review required before posting)*",
                "",
                "---",
                "",
                f"**Original description preview:** {issue_body[:200]}..."
                if len(issue_body) > 200
                else f"**Original description:** {issue_body}",
            ]
            return "\n".join(lines)

        return self._llm_or_fallback(system, user, fallback)
