"""Generate dev.to article drafts based on project releases."""

from .config import PromoterConfig
from .llm_adapter import LLMAdapter


class DevToGenerator:
    """Generate dev.to article drafts."""

    def __init__(self, config: PromoterConfig, llm: LLMAdapter | None = None) -> None:
        self.config = config
        self.llm = llm

    def generate_article(
        self,
        version: str,
        release_notes: str,
    ) -> str:
        """Generate a dev.to article draft for a release."""
        name = self.config.project_name
        repo = f"https://github.com/{self.config.github_owner}/{self.config.github_repo}"
        url = self.config.project_url

        system = (
            "You are a technical writer for developer blogs. "
            "Write engaging, informative dev.to articles about open-source releases."
        )
        user = (
            f"Write a dev.to article announcing {name} {version}.\n\n"
            f"Release notes:\n{release_notes[:1000]}\n\n"
            f"Include: what the project does, why it matters, key features in this release, "
            f"how to get started, and a call to action. Use markdown formatting, code blocks, "
            f"and emojis where appropriate. Keep it under 800 words.\n\n"
            f"Repo: {repo}\nWebsite: {url}"
        )

        if self.llm and self.llm.is_available():
            try:
                return (
                    self.llm.generate(system, user)
                    or self._fallback_article(version, release_notes)
                )
            except Exception:
                return self._fallback_article(version, release_notes)
        return self._fallback_article(version, release_notes)

    def _fallback_article(self, version: str, release_notes: str) -> str:
        """Rule-based fallback article."""
        name = self.config.project_name
        repo = f"https://github.com/{self.config.github_owner}/{self.config.github_repo}"
        url = self.config.project_url
        desc = self.config.project_description

        lines = [
            f"---",
            f"title: Announcing {name} {version}",
            f"published: false",
            f"tags: opensource, ai, memory, mcp",
            f"---",
            f"",
            f"# Announcing {name} {version} 🚀",
            f"",
            f"{desc}",
            f"",
            f"## What's new in {version}",
            f"",
            f"{release_notes[:500]}..." if len(release_notes) > 500 else release_notes,
            f"",
            f"## Why it matters",
            f"",
            f"AI agents need persistent memory to be truly useful. {name} solves this "
            f"with a local-first approach that keeps your data private and accessible.",
            f"",
            f"## Get started",
            f"",
            f"```bash",
            f"pip install truenex-memory",
            f"truenex-mem --help",
            f"```",
            f"",
            f"## Links",
            f"",
            f"- 🌐 [Website]({url})",
            f"- 📦 [GitHub]({repo})",
            f"- 📖 [Documentation]({repo}#readme)",
            f"",
            f"---",
            f"",
            f"*Generated by Truenex Promoter — review before publishing.*",
        ]
        return "\n".join(lines)
