"""Generate Product Hunt launch material."""

from .config import PromoterConfig
from .llm_adapter import LLMAdapter


class ProductHuntGenerator:
    """Generate Product Hunt launch page content."""

    def __init__(self, config: PromoterConfig, llm: LLMAdapter | None = None) -> None:
        self.config = config
        self.llm = llm

    def generate_launch(self, version: str = "") -> str:
        """Generate Product Hunt launch page content."""
        name = self.config.project_name
        repo = f"https://github.com/{self.config.github_owner}/{self.config.github_repo}"
        url = self.config.project_url
        desc = self.config.project_description

        system = (
            "You are a Product Hunt launcher. Write compelling, concise launch copy "
            "that makes developers want to try the product."
        )
        user = (
            f"Write Product Hunt launch copy for {name}.\n\n"
            f"Description: {desc}\n"
            f"Website: {url}\n"
            f"Repo: {repo}\n"
            f"Version: {version}\n\n"
            f"Include: tagline (60 chars max), description (260 chars max), "
            f"first comment from maker, and 3 key features."
        )

        if self.llm and self.llm.is_available():
            try:
                return self.llm.generate(system, user) or self._fallback_launch(version)
            except Exception:
                return self._fallback_launch(version)
        return self._fallback_launch(version)

    def _fallback_launch(self, version: str = "") -> str:
        """Rule-based fallback launch material."""
        name = self.config.project_name
        repo = f"https://github.com/{self.config.github_owner}/{self.config.github_repo}"
        url = self.config.project_url
        desc = self.config.project_description

        lines = [
            f"# Product Hunt Launch: {name}",
            f"",
            f"## Tagline (max 60 chars)",
            f"AI memory store that keeps agents in context",
            f"",
            f"## Description (max 260 chars)",
            f"{desc[:250]}..." if len(desc) > 250 else desc,
            f"",
            f"## First Comment (from Maker)",
            f"",
            f"Hey Product Hunters! 👋",
            f"",
            f"We built {name} because every AI agent we used kept forgetting context "
            f"between sessions. This is a local-first, open-source memory store that "
            f"helps agents remember what they learned across projects.",
            f"",
            f"It's not a database — it's context. Agents query it with natural language, "
            f"get back relevant memory chunks, and stay coherent across conversations.",
            f"",
            f"**Key features:**",
            f"- 🔍 Global search across all projects",
            f"- 🧠 Persistent memory for AI agents",
            f"- 🔌 MCP server integration",
            f"",
            f"Try it: {url}",
            f"Star us: {repo}",
            f"",
            f"## Gallery Images Needed",
            f"- [ ] Screenshot of CLI interface",
            f"- [ ] Diagram of memory architecture",
            f"- [ ] Demo GIF of agent using memory",
            f"",
            f"---",
            f"",
            f"*Generated by Truenex Promoter — review before submitting.*",
        ]
        return "\n".join(lines)
