"""Find relevant Stack Overflow questions for the project."""

import json
import urllib.parse
import urllib.request
from typing import Any

from .config import PromoterConfig


class StackOverflowFinder:
    """Find Stack Overflow questions that match project tags."""

    def __init__(self, config: PromoterConfig) -> None:
        self.config = config

    def find_questions(self, max_results: int = 10) -> list[dict[str, Any]]:
        """Find unanswered or recent questions matching project tags."""
        tags = ";".join(self.config.project_tags)
        url = (
            f"https://api.stackexchange.com/2.3/search"
            f"?order=desc&sort=creation&tagged={urllib.parse.quote(tags)}"
            f"&site=stackoverflow&pagesize={max_results}"
        )

        try:
            req = urllib.request.Request(url)
            req.add_header("Accept", "application/json")
            req.add_header("User-Agent", "truenex-promoter/0.1.0")
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                items = data.get("items", [])
                return [
                    {
                        "title": item.get("title", ""),
                        "url": item.get("link", ""),
                        "question_id": item.get("question_id", 0),
                        "score": item.get("score", 0),
                        "answer_count": item.get("answer_count", 0),
                        "view_count": item.get("view_count", 0),
                        "tags": item.get("tags", []),
                        "is_answered": item.get("is_answered", False),
                    }
                    for item in items
                    if not item.get("is_answered", True)  # Focus on unanswered
                ]
        except Exception:
            return []

    def generate_draft(self, question: dict[str, Any]) -> str:
        """Generate a draft answer for a Stack Overflow question."""
        name = self.config.project_name
        repo = f"https://github.com/{self.config.github_owner}/{self.config.github_repo}"
        desc = self.config.project_description

        lines = [
            f"## Draft Answer: {question.get('title', '')}",
            "",
            f"**Question:** {question.get('url', '')}",
            "",
            f"Hi! You might want to check out **{name}** — {desc}",
            "",
            f"**What it does:**",
            f"- {desc}",
            f"- Open-source ({repo})",
            f"- Apache 2.0 license",
            "",
            f"**How it could help with your question:**",
            "*(Review and customize this section based on the specific question)*",
            "",
            "---",
            "",
            f"*Draft generated by Truenex Promoter. Review before posting.*",
        ]
        return "\n".join(lines)
