"""Executor for Awesome List PR actions."""

from ..action_queue import Action
from .base import Executor


class AwesomePRExecutor(Executor):
    """Generate ready-to-use Awesome List PR material."""

    def can_execute(self, action: Action) -> bool:
        return action.type == "awesome_pr"

    def execute(self, action: Action) -> dict[str, str]:
        target_url = action.target_url
        draft = action.draft_content
        project = self.config.project_name
        repo = f"https://github.com/{self.config.github_owner}/{self.config.github_repo}"

        # Build instructions
        instructions = [
            f"# PR Material: Add {project} to Awesome List",
            "",
            f"**Target:** {target_url}",
            f"**Project Repo:** {repo}",
            f"**Project Website:** {self.config.project_url}",
            "",
            "## PR Title",
            f"Add {project} to the list",
            "",
            "## PR Body",
            "```markdown",
            draft,
            "```",
            "",
            "## Step-by-Step Instructions",
            "",
            "1. **Fork** the target repository:",
            f"   {target_url}/fork",
            "",
            "2. **Edit** the README.md in your fork:",
            "   - Add the project to the appropriate section",
            "   - Follow the existing format (bullet list, alphabetical order if applicable)",
            "",
            "3. **Create the PR** using the title and body above:",
            f"   {target_url}/compare/main...{self.config.github_owner}:main?expand=1",
            "",
            "4. **Wait for review** — maintainers usually respond within a few days.",
            "",
            "---",
            "",
            "*Generated by Truenex Promoter — review before submitting.*",
        ]

        content = "\n".join(instructions)
        path = self._save_execution(action, content)

        # Open the target repo in browser
        self._open_browser(target_url)

        return {
            "success": True,
            "output_path": str(path),
            "message": (
                f"PR material saved to {path}\n"
                f"Browser opened to {target_url}\n"
                f"Follow the step-by-step instructions in the file to submit the PR."
            ),
            "url_to_open": target_url,
        }
