"""Executor for dev.to article actions."""

from ..action_queue import Action
from .base import Executor


class DevToArticleExecutor(Executor):
    """Generate ready-to-use dev.to article material."""

    def can_execute(self, action: Action) -> bool:
        return action.type == "devto_article"

    def execute(self, action: Action) -> dict[str, str]:
        draft = action.draft_content
        version = action.data.get("tag", "")

        content = [
            f"# dev.to Article: {action.title}",
            "",
            "## Draft Article",
            "",
            "```markdown",
            draft,
            "```",
            "",
            "## Instructions",
            "",
            "1. Go to https://dev.to/new",
            "2. Paste the article (without ``` markers)",
            "3. Add a cover image (screenshot, diagram, or logo)",
            "4. Add tags: #opensource #ai #memory #mcp",
            "5. Click 'Publish'",
            "",
            "**Tips:**",
            "- Post on Tuesday-Thursday for maximum visibility",
            "- Share on Twitter/X and LinkedIn after publishing",
            "- Cross-post to Hashnode and Medium if desired",
            "",
            "---",
            "",
            "*Generated by Truenex Promoter — review before publishing.*",
        ]

        text = "\n".join(content)
        path = self._save_execution(action, text)
        self._open_browser("https://dev.to/new")

        return {
            "success": True,
            "output_path": str(path),
            "message": (
                f"Article saved to {path}\n"
                f"Browser opened to dev.to editor\n"
                f"Review the draft, add images, then publish."
            ),
            "url_to_open": "https://dev.to/new",
        }
