"""Executor for Product Hunt launch actions."""

from ..action_queue import Action
from .base import Executor


class ProductHuntLaunchExecutor(Executor):
    """Generate ready-to-use Product Hunt launch material."""

    def can_execute(self, action: Action) -> bool:
        return action.type == "producthunt_launch"

    def execute(self, action: Action) -> dict[str, str]:
        draft = action.draft_content
        url = self.config.project_url
        repo = f"https://github.com/{self.config.github_owner}/{self.config.github_repo}"

        content = [
            f"# Product Hunt Launch: {self.config.project_name}",
            "",
            "## Launch Material",
            "",
            "```markdown",
            draft,
            "```",
            "",
            "## Instructions",
            "",
            "1. Go to https://www.producthunt.com/posts/new",
            "2. Fill in the form using the material above",
            "3. Upload gallery images (required):",
            "   - Screenshot of the tool in action",
            "   - Architecture diagram",
            "   - Team photo or logo",
            "4. Schedule for Tuesday at 00:01 PST (best time)",
            "5. Prepare a 'first comment' as the maker",
            "",
            "**Tips:**",
            "- Launch on Tuesday for max visibility",
            "- Engage with every comment in the first 4 hours",
            "- Share on Twitter/X, LinkedIn, and relevant Slack/Discord communities",
            "- Have your team upvote in the first hour",
            "",
            "**Pre-launch checklist:**",
            "- [ ] Gallery images ready (min 3, recommended 5)",
            "- [ ] First comment drafted",
            "- [ ] Twitter/X post ready to share",
            "- [ ] LinkedIn post ready to share",
            "- [ ] Community announcements prepared (Reddit, HN, dev.to)",
            "",
            "---",
            "",
            "*Generated by Truenex Promoter — review before launching.*",
        ]

        text = "\n".join(content)
        path = self._save_execution(action, text)
        self._open_browser("https://www.producthunt.com/posts/new")

        return {
            "success": True,
            "output_path": str(path),
            "message": (
                f"Launch material saved to {path}\n"
                f"Browser opened to Product Hunt submission page\n"
                f"Review the draft, prepare images, then submit."
            ),
            "url_to_open": "https://www.producthunt.com/posts/new",
        }
