"""Executor for social media post actions."""

from ..action_queue import Action
from .base import Executor


class SocialPostExecutor(Executor):
    """Generate ready-to-use social media post material."""

    def can_execute(self, action: Action) -> bool:
        return action.type == "social_post"

    def execute(self, action: Action) -> dict[str, str]:
        draft = action.draft_content
        project = self.config.project_name
        repo = f"https://github.com/{self.config.github_owner}/{self.config.github_repo}"

        content = [
            f"# Social Media Post: {project}",
            "",
            "## LinkedIn",
            "",
            "```",
            draft,
            "```",
            "",
            "**Instructions:**",
            "1. Go to https://www.linkedin.com/post/new",
            "2. Copy the text above (without the ``` markers)",
            "3. Add an image if available (screenshot, logo, demo GIF)",
            "4. Tag relevant people/organizations",
            "5. Post!",
            "",
            "## Twitter / X",
            "",
            "```",
            self._to_twitter(draft),
            "```",
            "",
            "**Instructions:**",
            "1. Go to https://twitter.com/compose/tweet",
            "2. Copy the text above",
            "3. Add media if available",
            "4. Post!",
            "",
            "## dev.to",
            "",
            f"Consider writing a short article: https://dev.to/new",
            f"Title: Announcing {project} — {self.config.project_description[:80]}...",
            "",
            "---",
            "",
            "*Generated by Truenex Promoter — review before posting.*",
        ]

        text = "\n".join(content)
        path = self._save_execution(action, text)

        # Open LinkedIn post composer
        self._open_browser("https://www.linkedin.com/post/new")

        return {
            "success": True,
            "output_path": str(path),
            "message": (
                f"Social post material saved to {path}\n"
                f"Browser opened to LinkedIn post composer\n"
                f"Review the draft, add media, then post."
            ),
            "url_to_open": "https://www.linkedin.com/post/new",
        }

    def _to_twitter(self, text: str) -> str:
        """Convert a long post to Twitter-friendly version (max 280 chars)."""
        lines = text.strip().split("\n")
        # Take first 2-3 lines, add link
        short = " ".join(lines[:3])[:200]
        repo = f"https://github.com/{self.config.github_owner}/{self.config.github_repo}"
        return f"{short}... 👉 {repo} #opensource #ai"
