"""Executor for Stack Overflow answer actions."""

from ..action_queue import Action
from .base import Executor


class StackOverflowAnswerExecutor(Executor):
    """Generate ready-to-use Stack Overflow answer material."""

    def can_execute(self, action: Action) -> bool:
        return action.type == "stackoverflow_answer"

    def execute(self, action: Action) -> dict[str, str]:
        draft = action.draft_content
        target_url = action.target_url
        question_title = action.data.get("title", "")

        content = [
            f"# Stack Overflow Answer: {question_title}",
            "",
            f"**Question:** {target_url}",
            "",
            "## Draft Answer",
            "",
            "```markdown",
            draft,
            "```",
            "",
            "## Instructions",
            "",
            "1. Open the question URL above",
            "2. Click 'Your Answer' at the bottom",
            "3. Paste the draft (without ``` markers)",
            "4. Review and customize the answer",
            "5. Click 'Post Your Answer'",
            "",
            "**Tips:**",
            "- Be helpful, not promotional",
            "- Answer the question first, then mention your project",
            "- Include code examples if relevant",
            "",
            "---",
            "",
            "*Generated by Truenex Promoter — review before posting.*",
        ]

        text = "\n".join(content)
        path = self._save_execution(action, text)
        self._open_browser(target_url)

        return {
            "success": True,
            "output_path": str(path),
            "message": (
                f"Answer material saved to {path}\n"
                f"Browser opened to Stack Overflow question\n"
                f"Review the draft, customize, then post."
            ),
            "url_to_open": target_url,
        }
